[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "{{ project_name }}.settings"
python_files = "test_*.py *_tests.py tests/*"
log_level = "DEBUG"

[tool.coverage.run]
omit = [
    "*/admin.py",
    "*/manage.py",
    "*/migrations/*",
    "*/tests/*",
    "conftest.py",
]

[tool.mypy]
plugins = [
    "mypy_django_plugin.main",
]
exclude = [
    'static/',
    'templates/',
    '.sh',
    'admin\.py$',
    'Dockerfile',
]
disable_error_code = "import-untyped"

[tool.django-stubs]
django_settings_module = "{{ project_name }}.settings"

