[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "{{ project_name }}.settings"
python_files = "test_*.py *_tests.py tests/*"
log_level = "DEBUG"

[tool.coverage.run]
omit = [
    "*/admin.py",
    "*/manage.py",
    "*/migrations/*",
    "*/tests/*",
    "conftest.py",
]

[tool.mypy]
plugins = [
    "mypy_django_plugin.main",
]
exclude = [
    'static/',
    'templates/',
    '.sh',
    'admin\.py$',
    'Dockerfile',
]
disable_error_code = "import-untyped"

[tool.django-stubs]
django_settings_module = "{{ project_name }}.settings"

[tool.ruff]
line-length = 100
indent-width = 4
exclude = [
    ".git",
    "venv",
    ".venv",
    ".idea"
]
target-version = "py310"

[tool.ruff.lint]
select = ["COM812"]
ignore = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

docstring-code-format = true
docstring-code-line-length = 100

